In [1]:
import numpy as np

## Crossover

Существуют различные методы определения пересечения в случае генетических алгоритмов, такие как одноточечный, двухточечный и k-точечный кроссовер, равномерный кроссовер и кроссовер для упорядоченных списков. Мы будем использовать единый кроссовер, где каждый параметр для ребенка (нового объекта популяции) будет независимо выбираться из родителей на основе определенного распределения.

В качестве дз реализуем кроссовер Ордена Дэвиса (OX1)

Пусть у нас есть 2 родителя с набором из 15 генов

In [12]:
parent_1 = np.random.randint(0, 50, 15)
parent_1

array([22, 11, 15, 22,  2, 39, 20,  9, 46, 20, 19, 30,  0,  9, 19])

In [15]:
parent_1.shape[0]

15

In [13]:
parent_2 = np.random.randint(0, 50, 15)
parent_2

array([17, 39, 43, 16, 19, 24, 41, 11, 49,  7,  7,  9,  6, 40, 35])

Случайным образом инициализируем окно, в котором оставим гены первого родителя

In [39]:
window = np.sort(np.random.randint(1, parent_1.shape[0], 2))
window

array([ 6, 12])

И в потомке оставим гены первого родителя в этом случайном окне

In [42]:
child = np.zeros(parent_1.shape)

In [46]:
child[window[0]:window[1]] = parent_1[window[0]:window[1]]

In [47]:
child

array([ 0.,  0.,  0.,  0.,  0.,  0., 20.,  9., 46., 20., 19., 30.,  0.,
        0.,  0.])

Теперь, удалим из второго родителя те значения, которые попали в это окно от первого

In [56]:
parent_2_tmp = np.setdiff1d(parent_2, child, assume_unique=True)
parent_2_tmp

array([17, 39, 43, 16, 24, 41, 11, 49,  7,  6, 40, 35])

и теперь заполним оставшиеся значения ребенка этими

In [61]:
child[:window[0]] = parent_2_tmp[:window[0]]

In [62]:
child

array([17., 39., 43., 16., 24., 41., 20.,  9., 46., 20., 19., 30.,  0.,
        0.,  0.])

In [71]:
child[window[1]:] = parent_2_tmp[window[0] : window[0] + child[window[1]:].shape[0]]

In [74]:
child

array([17., 39., 43., 16., 24., 41., 20.,  9., 46., 20., 19., 30., 11.,
       49.,  7.])

то же самое надо повторить для второго ребенка, но взять окно от второго родителя

напишем функцию

In [80]:
def crossover_uniform(parents, children_size):
    """
    
    """
    children = np.empty(children_size)
    
    for i in range(children_size[0]):
        if i != children_size[0]-1:
            window = np.sort(np.random.randint(1, parents[i].shape[0], 2))
            parent_1 = parents[i]
            parent_2 = parents[i + 1]
            child = np.zeros(parent_1.shape)
            child[window[0]:window[1]] = parent_1[window[0]:window[1]]
            parent_2_tmp = np.setdiff1d(parent_2, child, assume_unique=True)
            child[:window[0]] = parent_2_tmp[:window[0]]
            child[window[1]:] = parent_2_tmp[window[0] : window[0] + child[window[1]:].shape[0]]
            children[i] = child
        else:
            window = np.sort(np.random.randint(1, parents[i].shape[0], 2))
            parent_1 = parents[i]
            parent_2 = parents[0]         # берем первого родителя и скрещиваем с последним
            child = np.zeros(parent_1.shape)
            child[window[0]:window[1]] = parent_1[window[0]:window[1]]
            parent_2_tmp = np.setdiff1d(parent_2, child, assume_unique=True)
            child[:window[0]] = parent_2_tmp[:window[0]]
            child[window[1]:] = parent_2_tmp[window[0] : window[0] + child[window[1]:].shape[0]]
            children[i] = child
        
        
    return children

Это конечно не сработает для примера из методички, так как тут перемешиваются признаки с разными ограничениями, но если на всех признаках одинаковые ограничения - то должно работать)

алгоритм взят отсюда http://www.rubicite.com/Tutorials/GeneticAlgorithms/CrossoverOperators/Order1CrossoverOperator.aspx